### ISSUE TITLE
How can I validate the source code in this chart?

### ISSUE THREAD

**Issue by stefanlasiewski** [bitnami/bitnami-docker-external-dns#8]
On Friday, our external DNS service suffered a major problem which took is 4 hours to fix. 

We use the RFC2136 provider and suffered from this known issue:

```
{"log":"time=\"2021-02-20T01:26:19Z\" level=info msg=\"error in dns.Client.Exchange: dns: message too large\"\n","stream":"stderr","time":"2021-02-20T01:26:19.395974618Z"}
{"log":"time=\"2021-02-20T01:26:19Z\" level=error msg=\"RFC2136 update failed: dns: message too large\"\n","stream":"stderr","time":"2021-02-20T01:26:19.395994836Z"}
```

This should have been fixed in 0.7.2 as part of kubernetes-sigs/external-dns/pull/1590 as shown in the following release notes:

https://github.com/kubernetes-sigs/external-dns/blob/master/CHANGELOG.md#v072---2020-06-03

Even so, we still ran into this problem (or, least one that was very similar!)

Is there a way for me to verify with 100% certainty that source code used by the Bitnami chart does indeed include the fix? I'd like to be able to see that the [9 line of code](https://github.com/kubernetes-sigs/external-dns/pull/1590/files) really is present in our chart.

**Comment by marcosbc** [comment]
Hi @stefanlasiewski, if you used any 0.7.6 release of the Bitnami Docker image for External DNS, I can confirm those lines are included in the source code.

For checking this, I can provide the checksums for the tarballs we have used to build the source since 0.7.2:

* 0.7.6: `c554939f96d33caff3e7b68bbf4f7ce56ac615cea194a21d1e56bbef55789803`
* 0.7.5: `dee624126306f792d04566c9b5863ab963e2eddbcd2daa25e2ca4b99cec9e218`
* 0.7.4: `74f268efefb64dcbf7b48a2509799ef9d4bab1f04deb8bdb56ee06aaae23c3b5`
* 0.7.3: `3353558b6d1bd655f777491eaad3202a98f3a8ee86c8857960908cde5ea43842`
* 0.7.2: `dc063fa9b940e81c81ff01bece030a32955c8bb638be9225b18536ec12ed1445`

We download the tarballs from an URL matching the below pattern (where `{{version}}` is the External DNS version, i.e. 0.7.2):

```
https://codeload.github.com/kubernetes-incubator/external-dns/tar.gz/v{{version}}
```

Let us know if you have any questions.
